db:
  image: 'postgres:13.1-alpine'
  container_name: db
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=cooperativa

rabbitmq:
  image: rabbitmq:3-management
  container_name: rmq
  ports:
    - "5672:5672"
    - "15672:15672"
    - "25672:25672"
    - "4369:4369"