logging:
  level:
    br:
      com:
        gumillanf: DEBUG

server:
  port: 8081

spring:
  application:
    name: cooperativa

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      result: exchangeresult
    queue:
      result: queueresult
    routingkey:
      result: routingkeyresult

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_size: 1000
        rewriteBatchedStatements: true
        cachePrepStmts: true
        useServerPrepStmts: true
        generate_statistics: false
        format_sql: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cooperativa
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

app:
  schedule:
    finalized: 0 0/5 * * * *

